using System.Runtime.CompilerServices;
using Godot;
using SpartansLib;
using static SpartansLib.Logger;

namespace SpartansLib.Common
{
    public static class LoggerExtensions
    {
        public static void Print(this Node self, params object[] what)
            => GD.Print(what);

        public static void PrintS(this Node self, params object[] what)
            => GD.PrintS(what);

        public static void PrintT(this Node self, params object[] what)
            => GD.PrintT(what);

        public static void PrintErr(this Node self, params object[] what)
            => GD.PrintErr(what);

        public static void PrintRaw(this Node self, params object[] what)
            => GD.PrintRaw(what);

        public static void PrintStack(this Node self)
            => GD.PrintStack();

        public static void Log(this Node self,
            LogLevel level,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Log(level,
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

        public static void Verbose(this Node self,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Verbose(
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

        public static void Debug(this Node self,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Debug(
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

        public static void Info(this Node self,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Info(
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

        public static void Warn(this Node self,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Warn(
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

        public static void Error(this Node self,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Error(
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

        public static void Fatal(this Node self,
            object arg0 = null,
            object arg1 = null,
            object arg2 = null,
            object arg3 = null,
            object arg4 = null,
            object arg5 = null,
            object arg6 = null,
            object arg7 = null,
            object arg8 = null,
            object arg9 = null,
            object arg10 = null,
            object arg11 = null,
            object arg12 = null,
            object arg13 = null,
            object arg14 = null,
            object arg15 = null,
            object arg16 = null,
            object arg17 = null,
            object arg18 = null,
            object arg19 = null,
            object arg20 = null,
            [CallerMemberName] string memberName = "",
            [CallerFilePath] string sourceFilePath = "",
            [CallerLineNumber] int sourceLineNumber = 0
        ) => Logger.Fatal(
                arg0,
                arg1,
                arg2,
                arg3,
                arg4,
                arg5,
                arg6,
                arg7,
                arg8,
                arg9,
                arg10,
                arg11,
                arg12,
                arg13,
                arg14,
                arg15,
                arg16,
                arg17,
                arg18,
                arg19,
                arg20,
                memberName,
                sourceFilePath,
                sourceLineNumber);

    }
}
